version: '3'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lexter-algorithm-interview
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
    volumes:
      - .:/app