version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: lexter-algorithm-interview-prod
    ports:
      - "3000:3000"
    environment:
      - PORT=3000